### ISSUE TITLE
Moderation commands with timed versions where relevant

### ISSUE THREAD

**Issue by rasmusgerdin** [RTByte/RTByte#10]
- [x] Ban
- [x] Softban
- [x] Kick
- [x] Mute (timed)
- [x] Unmute
- [x] Serverinfo
- [x] Userinfo
- [x] Warn
- [x] Purge
- [x] Send message
- [x] VC kick
- [x] VC ban (timed)
- [x] VC unban

**Comment by mcumbers** [comment]
Finished last commands (VC Moderation) in 0d5a7655efae4b682c26127076769eaa148b1d60
