### ISSUE TITLE
Switch over any avatarURL() calls to displayAvatarURL()

### ISSUE THREAD

**Issue by rasmusgerdin** [RTByte/RTByte#14]
avatarURL() returns the user's profile picture if they have one
https://discord.js.org/#/docs/main/master/class/User?scrollTo=avatarURL

displayAvatarURL() returns the user's profile picture if they have one, and their default profile picture if they haven't added one yet
https://discord.js.org/#/docs/main/stable/class/User?scrollTo=displayAvatarURL

**Comment by mcumbers** [comment]
9d88ef0c22bbb288c10626533d58384e7c4c5aa9
