### ISSUE TITLE
channelUpdate errors out on channels not in categories

### ISSUE THREAD

**Issue by mcumbers** [RTByte/RTByte#16]
https://github.com/RTByte/RTByte/commit/0208073bc584db6fcabb87a82610d8d7b49e1119#diff-11482cd5a89daf3bab9d8186f6432317

Comment added on Line 37

**Comment by mcumbers** [comment]
I'm going to bed, so I'm not fixing this for you 😂

**Comment by rasmusgerdin** [comment]
Fixing after work!
