### ISSUE TITLE
Server- and userinfo embeds fail because of max field length

### ISSUE THREAD

**Issue by rasmusgerdin** [RTByte/RTByte#18]
Urgent as bigger servers currently can't run serverinfo (tested on CC, AH)
Server- and userinfo embeds fail if the server has enough roles to (over)populate the list by hitting the max field length.

![image](https://i.imgur.com/gnJQcpT.jpg)

### Possible solutions:
Solution 1: Limit it by showing the (10?) highest roles according to the role hierarchy.
Solution 2: Split the field before 1024 characters and add a second one if needed.

**Comment by rasmusgerdin** [comment]
Temporarily fixed by reverting to showing the amount instead of the objects. Would be nice to look into ways of displaying the objects still. Again possibly by splitting to a new field, or showing X amount in accordance with the hierarchy with a cutoff point at 1020-ish characters.

**Comment by mcumbers** [comment]
545eed81f5d19d0efa99bd1bf9a2bfc6ee53b5f6
