### ISSUE TITLE
Why would you wanna do this way

### ISSUE THREAD

**Issue by Anish-Shobith** [RTByte/RTByte#21]
https://github.com/RTByte/RTByte/blob/e6151671420ee3352cbe6e1e7977c31a50282c46/src/index.js#L110
Not Really required

And you can basically do
```js
new Client(config).login(token)
```
At line 
https://github.com/RTByte/RTByte/blob/e6151671420ee3352cbe6e1e7977c31a50282c46/src/index.js#L112

**Comment by mcumbers** [comment]
5e2cd7587b31bc92f831d827c1b49a3a7583ba58
