### ISSUE TITLE
Site down

### ISSUE THREAD

**Issue by jtagcat** [RTByte/rtbyte#45]
https://rtbyte.xyz/ -> Timeout

**Comment by rasmusgerdin** [comment]
We're working on a dashboard for the site, but haven't bothered getting a landing page up until that's actually finished. Will get a temporary page up in the meantime. Thanks for filing this, much appreciated!

**Comment by rasmusgerdin** [comment]
A landing page has now been put up, sorry it took so long :)
https://rtbyte.xyz/
