### ISSUE TITLE
antiInvite doesn't trigger unless there is at least one invite link whitelisted

### ISSUE THREAD

**Issue by rasmusgerdin** [RTByte/RTByte#5]
### Expected behavior:
When filters.antiInvite is enabled and no invite links have been added to filters.inviteWhitelist, all invite links should be deleted.
### Actual behavior:
When filters.antiInvite is enabled and no invite links have been added to filters.inviteWhitelist, the monitor triggers. After adding an invite link to filters.inviteWhitelist, the monitor triggers as normal.

**Comment by JShull97** [comment]
moved if(!msg.guild.settings.filters.inviteWhitelist.length) from the start of the run method to the nested loop of the cycleWords method.
